replicaCount: 1

image:
  repository: ghcr.io/andreeewill/kaipo
  tag: 'latest'
  pullPolicy: IfNotPresent
  # Optionally reference registry pull secrets (for private images)
  pullSecrets: []
  # - name: ghcr-pull

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

container:
  port: 3000
  env: []
  # - name: NODE_ENV
  #   value: production

# Kubernetes Secret to inject sensitive env values
secret:
  enabled: false
  # name: "" # defaults to <fullname>-secret when empty
  data: {}
  # DB_URL: postgres://user:pass@host:5432/db
  # JWT_SECRET: super-secret

ingress:
  enabled: true
  hosts:
    - host: api.kaipo.my.id
  annotations:
    # optional: add middlewares here
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  tls:
    enabled: false
    secretName: kaipo-tls

probes:
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 15
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10

nodeSelector: {}

affinity: {}

tolerations: []

fullnameOverride: kaipo
