{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secret" (include "kaipo.fullname" .)) .Values.secret.name }}
  labels:
    app.kubernetes.io/name: {{ include "kaipo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
